### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   ----- ---------------------------------- 1.6/12.4 MB 6.5 MB/s eta 0:00:02
   --------------- ------------------------ 4.7/12.4 MB 10.7 MB/s eta 0:00:01
   ------------------ --------------------- 5.8/12.4 MB 8.9 MB/s eta 0:00:01
   -------------------- ------------------- 6.3/12.4 MB 8.4 MB/s eta 0:00:01
   ----------------------- ---------------- 7.3/12.4 MB 7.1 MB/s eta 0:00:01
   -------------------------- ------------- 8.1/12.4 MB 6.4 MB/s eta 0:00:01
   -------------------------- ------------- 8.4/12.4 MB 5.9 MB/s eta 0:00:01
   ------------------------------ --------- 9.4/12.4 MB 5.5 MB/s eta 0:00:01
   -------------------------------- ------- 10.0/12.4 MB 5.4 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.4 MB 5.0 MB/s eta 0:00:01
   --------------

### Creating Numpy Arrays

In [1]:
# np.array
import numpy as np

# creating 1d array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# 2D
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [3]:
# 3d
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [7]:
# dtype
print(np.array([1,2,3],dtype=float))

print(np.array([1, 2, 3, 0, 0], dtype=bool))

print(np.array([1, 3, 45], dtype=str))

[1. 2. 3.]
[ True  True  True False False]
['1' '3' '45']


In [ ]:
# np.arange
# start included, end is EXCLUDED
print(np.arange(1,11))

print(np.arange(1, 11, 2)) # step size = 2

array([1, 3, 5, 7, 9])

In [15]:
# with RESHAPE

# if array contains 12 items, the shape (x, y) should be such that x * y = 12
print("(2, 6): \n" , np.arange(12).reshape(2, 6))
print("(6,2): \n", np.arange(12).reshape(6, 2))
print("(3, 4): \n", np.arange(12).reshape(3, 4))
# print(np.arange(12).reshape(5, 5)) #ERROR: 5*5 is not equal to the number of items.

(2, 6): 
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(6,2): 
 [[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]
(3, 4): 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [18]:
# np.ones and np.zeros
np.ones((3,4))

# np.ones((3,4), dtype=int) # dtype will be integer

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# np.random
# will initialize a random number between 0 and 1
np.random.random((3,4))

array([[0.85721156, 0.31248316, 0.08807828, 0.35230774],
       [0.96813914, 0.44681708, 0.56396358, 0.53020065],
       [0.03277116, 0.28543753, 0.09521082, 0.87967034]])

In [ ]:
# np.linspace -> linear space
# will generate linearly separable points
# for ex: between 1 and 10, 5 linearly spaced numbers are: 2, 4, 6, 8, 10

# syntax: np.linspace(startValue, stopValue, number of elemens, dtype)

np.linspace(-10,10,10,dtype=int) # both startValue and stopValue is included

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [ ]:
# np.identity
# identity matrix

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [31]:
a1 = np.arange(10,dtype=np.int32) #1d
a2 = np.arange(12,dtype=float).reshape(3,4) #2d
a3 = np.arange(8).reshape(2,2,2) #3d

In [23]:
# ndim
# tells the number of dimensions

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [24]:
# shape
# prints the number of rows and columns as a tuple
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [25]:
# size
# returns the total number of elements inside array
print(a1.size)
print(a2.size)
print(a2.size)

10
12
12


In [26]:
# itemsize
# size of the array in memory
print(a1.itemsize)
a3.itemsize

4


8

In [ ]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)



int32
float64
int64


### Changing Datatype

In [33]:
# astype
# reduce the data type to save memory
# a3 currenlty occupies 8 bytes in memory (np.int64)
print(a3.itemsize) 

a4 = a3.astype(np.int32)

print(a4.itemsize)

8
4


### Array Operations

In [38]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [39]:
# scalar operations

# arithmetic
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [40]:
# relational
# a1 > 25

a2 == 15

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [41]:
# vector operations
# arithmetic
# a1 + a1
# a1 / a1
a1 ** a2

array([[                   0,                    1,                16384,
                    14348907],
       [          4294967296,         762939453125,      101559956668416,
           11398895185373143],
       [ 1152921504606846976, -1261475310744950487,  1864712049423024128,
         6839173302027254275]])

### Array Functions

In [43]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[35., 27.,  9.],
       [31., 78., 55.],
       [19., 47., 95.]])

In [52]:
# max/min/sum/prod

# return ONE RESULT from the entire array.
print(np.max(a1))

print(np.min(a1))
print(np.sum(a1))

# What if i need to apply operations on columns / rows?
# 0 -> col and 1 -> row
print(np.prod(a1,axis=0)) # returns product of each column
np.sum(a1, axis=1) # sum of each row

95.0
9.0
396.0
[20615. 98982. 47025.]


array([ 71., 164., 161.])

In [54]:
# mean/median/std/var
np.mean(a1, axis=0)
# np.var(a1,axis=1)

array([28.33333333, 50.66666667, 53.        ])

In [ ]:
# trigonomoetric functions
np.sin(a1)

array([[-0.83177474,  0.27090579,  0.95105465],
       [ 0.95637593, -0.94828214, -0.99177885],
       [-0.40403765, -0.75098725,  0.6569866 ]])

In [ ]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [ ]:
# log and exponents
np.exp(a1)

array([[4.72783947e+18, 1.44625706e+12, 6.83767123e+30],
       [5.32048241e+11, 2.45124554e+40, 4.31123155e+15],
       [2.90488497e+13, 6.56599691e+07, 1.09663316e+03]])

In [57]:
# round/floor/ceil
np.round(np.random.random((2, 3)) * 100)
# np.floor(np.random.random((2, 3)) * 100)
# np.ceil(np.random.random((2,3))*100)

array([[ 0., 65., 52.],
       [31.,  0., 96.]])

### Indexing and Slicing

In [65]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
# Indexing
# syntax: arrayName[rowNumber, colNumber]

a2[1,0]

4

In [ ]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [ ]:
a3[1,0,1]

5

In [ ]:
a3[1,1,0]

6

In [ ]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
# SLICING

a1[2:5:2] # 2nd index to 5th index. 5th EXCLUDED. stride/step value: 2 ( alternate elements )

array([2, 4])

In [ ]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
a2[0:2,1::2]

array([[1, 3],
       [5, 7]])

In [ ]:
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [ ]:
a2[1,::3]

array([4, 7])

In [ ]:
a2[0,:]

array([0, 1, 2, 3])

In [ ]:
a2[:,2]

array([ 2,  6, 10])

In [ ]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

### Iterating

In [61]:
a1

for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [69]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [63]:
for i in a2:
  print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [66]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [64]:
for i in a3:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [70]:
# prints each value in 2d / 3d array
for i in np.nditer(a2):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11


### Reshaping

In [ ]:
# reshape

In [75]:
# TRANSPOSE
# 1. np.transpose()
# 2. arraName.T

print(np.transpose(a2))
a2.T 

[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [90]:
a3[0,0,1] = 1

In [91]:
# RAVEL
# ravel flattens a multidimensional array into 1d without copying the data.
# changes in flattened array also reflects in original array.

b = a3.ravel()
b[1] = 100
print(id(a3[0,0,1]))
print(id(b[1]))

2415147914352
2415147913968


In [92]:
a3


array([[[  0, 100],
        [  2,   3]],

       [[  4,   5],
        [  6,   7]]])

### Stacking

In [94]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)
print(a4, end='\n\n\n')
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [95]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [96]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

### Splitting

In [98]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
# np.hsplit(arrayName, NumberOfSplits)
np.hsplit(a4,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [ ]:
# vertical splitting

In [ ]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [103]:
np.vsplit(a5,2)

ValueError: array split does not result in an equal division

In [107]:
a6 = np.arange(16).reshape(8, 2)
a6

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [110]:
np.vsplit(a6, 4)

[array([[0, 1],
        [2, 3]]),
 array([[4, 5],
        [6, 7]]),
 array([[ 8,  9],
        [10, 11]]),
 array([[12, 13],
        [14, 15]])]