### np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [4]:
# code
import numpy as np
a = np.random.randint(1,100,15) # random 15 numbers between 1 and 100 
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [5]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[85, 80, 72, 72],
       [50, 92, 74, 82],
       [35, 88, 27, 77],
       [89, 73, 97, 52],
       [73, 69, 31, 97],
       [61, 82, 37,  3]], dtype=int32)

In [6]:
# sorting in ascending order
# returns a numpy array
np.sort(a)

array([11, 27, 44, 51, 65, 66, 68, 71, 73, 77, 83, 87, 91, 97, 98],
      dtype=int32)

In [10]:
# sorting in descending order
# np.sort doesn't have reverse=true parameter
np.sort(a)[::-1]

array([98, 97, 91, 87, 83, 77, 73, 71, 68, 66, 65, 51, 44, 27, 11],
      dtype=int32)

In [12]:
# Sorting 2d 
# by rows, axis = 1
# by column, axis = 0
np.sort(b,axis=1)

array([[72, 72, 80, 85],
       [50, 74, 82, 92],
       [27, 35, 77, 88],
       [52, 73, 89, 97],
       [31, 69, 73, 97],
       [ 3, 37, 61, 82]], dtype=int32)

In [9]:
np.sort(b, axis = 0)

array([[35, 69, 27,  3],
       [50, 73, 31, 52],
       [61, 80, 37, 72],
       [73, 82, 72, 77],
       [85, 88, 74, 82],
       [89, 92, 97, 97]], dtype=int32)

### np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html

In [11]:
# code
# adds a number at the end of array
np.append(a,200)

array([ 65,  51,  98,  77,  83,  44,  68,  87,  66,  27,  97,  73,  11,
        71,  91, 200])

In [14]:
b

array([[85, 80, 72, 72],
       [50, 92, 74, 82],
       [35, 88, 27, 77],
       [89, 73, 97, 52],
       [73, 69, 31, 97],
       [61, 82, 37,  3]], dtype=int32)

In [18]:
b.shape

(6, 4)

In [20]:
# appending an entire column to an array
# col: axis = 1
np.append(b, np.ones((b.shape[0], 1)), axis=1)

array([[85., 80., 72., 72.,  1.],
       [50., 92., 74., 82.,  1.],
       [35., 88., 27., 77.,  1.],
       [89., 73., 97., 52.,  1.],
       [73., 69., 31., 97.,  1.],
       [61., 82., 37.,  3.,  1.]])

In [21]:
# appending an entire row
# row: axis = 0
np.append(b, np.ones((1, b.shape[1])), axis=0)

array([[85., 80., 72., 72.],
       [50., 92., 74., 82.],
       [35., 88., 27., 77.],
       [89., 73., 97., 52.],
       [73., 69., 31., 97.],
       [61., 82., 37.,  3.],
       [ 1.,  1.,  1.,  1.]])

### np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [ ]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [ ]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

### np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [92]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])

In [93]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [95]:
np.unique(e, return_counts=True)

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 2, 2, 2]))

### np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [22]:
# code
a.shape

(15,)

In [30]:
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [34]:
# converting 1d to 2d: expanding row dimension
exp_a = np.expand_dims(a, axis=0)
exp_a

array([[65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91]],
      dtype=int32)

In [31]:
exp_a.shape

(1, 15)

In [33]:
# no change in original array
a.shape

(15,)

In [35]:
# explanding column dimension
np.expand_dims(a,axis=1)

array([[65],
       [51],
       [98],
       [77],
       [83],
       [44],
       [68],
       [87],
       [66],
       [27],
       [97],
       [73],
       [11],
       [71],
       [91]], dtype=int32)

### np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [37]:
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [ ]:
# find all indices with value greater than 50
np.where(a>50)

(array([ 1,  6,  7, 10, 12]),)

In [38]:
# replace all values > 50 with 0
# SYNTAX: np.where( condition, if true, if false )

# task: make all the elements which is greater that 60 to 0
np.where(a>60,0,a)

array([ 0, 51,  0,  0,  0, 44,  0,  0,  0, 27,  0,  0, 11,  0,  0],
      dtype=int32)

In [40]:
# task: turn all the elements which are even to 0.
np.where(a%2 == 0,0,a)

array([65, 51,  0, 77, 83,  0,  0, 87,  0, 27, 97, 73, 11, 71, 91],
      dtype=int32)

### np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [41]:
# code
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [47]:
# here we can just pass the array and this will return the index of maximum element in it.
np.argmax(a)

np.int64(2)

In [43]:
b

array([[85, 80, 72, 72],
       [50, 92, 74, 82],
       [35, 88, 27, 77],
       [89, 73, 97, 52],
       [73, 69, 31, 97],
       [61, 82, 37,  3]], dtype=int32)

In [48]:
# in a 2d array, axis=0 will print the index of max element column wise.
np.argmax(b,axis=0)

array([3, 1, 3, 4])

In [50]:
# row-wise index of max element.
np.argmax(b,axis=1)

array([0, 1, 1, 2, 3, 1])

In [51]:
# np.argmin
np.argmin(a)

np.int64(12)

### np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [ ]:
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [52]:
np.cumsum(a)

array([  65,  116,  214,  291,  374,  418,  486,  573,  639,  666,  763,
        836,  847,  918, 1009])

In [53]:
b

array([[85, 80, 72, 72],
       [50, 92, 74, 82],
       [35, 88, 27, 77],
       [89, 73, 97, 52],
       [73, 69, 31, 97],
       [61, 82, 37,  3]], dtype=int32)

In [54]:
np.cumsum(b,axis=1)

array([[ 85, 165, 237, 309],
       [ 50, 142, 216, 298],
       [ 35, 123, 150, 227],
       [ 89, 162, 259, 311],
       [ 73, 142, 173, 270],
       [ 61, 143, 180, 183]])

In [55]:
np.cumsum(b)

array([  85,  165,  237,  309,  359,  451,  525,  607,  642,  730,  757,
        834,  923,  996, 1093, 1145, 1218, 1287, 1318, 1415, 1476, 1558,
       1595, 1598])

In [56]:
# np.cumprod: cumulative product
np.cumprod(a)

array([                  65,                 3315,               324870,
                   25014990,           2076244170,          91354743480,
              6212122556640,      540454662427680,    35670007720226880,
         963090208446125760,  1186029850726440640, -5653541265517591360,
       -6848721699564850112, -6643894752656015936,  4148131940717753152])

In [57]:
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

### np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis.

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [58]:
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [68]:
# SYNTAX: np.percentile(arrayName, percentile)
np.percentile(a,100) # 100th percentile-> maximum from array

np.float64(98.0)

In [69]:
np.percentile(a,0) # 0th percentile-> minimum number in array

np.float64(11.0)

In [70]:
np.median(a)

np.float64(71.0)

### np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [71]:
# code
a

array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [75]:
np.histogram(a, bins=[0, 10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# 0 elements between 0 and 10, 1 element between 10 and 20, 3 elements between 90 and 100.

(array([0, 1, 1, 0, 1, 1, 3, 3, 2, 3]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [74]:
np.histogram(a,bins=[0,50,100])

# 3 elements between 0 and 50 and 12 numbers between 50 and 100.

(array([ 3, 12]), array([  0,  50, 100]))

### np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [ ]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

### np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [77]:
# code
a


array([65, 51, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [79]:
items = [10,20,97,40,83,60,44,80,90,66]

# finds how many 
np.isin(a, items) # returns true/false in array 'a'

array([False, False, False, False,  True,  True, False, False,  True,
       False,  True, False, False, False, False])

In [81]:
a[np.isin(a,items)] # to get the exact numbers that are present in a and items

array([83, 44, 66, 97], dtype=int32)

### np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [ ]:
# code
a

array([11, 53, 28, 50, 38, 37, 94, 92,  5, 30, 68,  9, 78,  2, 21])

In [82]:
# provides a mirror image
np.flip(a)

array([91, 71, 11, 73, 97, 27, 66, 87, 68, 44, 83, 77, 98, 51, 65],
      dtype=int32)

In [83]:
b

array([[85, 80, 72, 72],
       [50, 92, 74, 82],
       [35, 88, 27, 77],
       [89, 73, 97, 52],
       [73, 69, 31, 97],
       [61, 82, 37,  3]], dtype=int32)

In [85]:
# both row and column flipping
np.flip(b)

array([[ 3, 37, 82, 61],
       [97, 31, 69, 73],
       [52, 97, 73, 89],
       [77, 27, 88, 35],
       [82, 74, 92, 50],
       [72, 72, 80, 85]], dtype=int32)

In [87]:
# row wise flipping
np.flip(b, axis=1)

array([[72, 72, 80, 85],
       [82, 74, 92, 50],
       [77, 27, 88, 35],
       [52, 97, 73, 89],
       [97, 31, 69, 73],
       [ 3, 37, 82, 61]], dtype=int32)

### np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array.

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [91]:
# code
a

array([99, 88, 98, 77, 83, 44, 68, 87, 66, 27, 97, 73, 11, 71, 91],
      dtype=int32)

In [90]:
# updates the original array
# syntax: np.put( arrayName, [indices], [newValues])
np.put(a,[0,1], [99, 88])

### np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis.

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.delete(a,[0,2,4])

array([530,  50,  37,  94,  92,   5,  30,  68,   9,  78,   2,  21])

### Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [ ]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
np.intersect1d(m,n)

array([3, 4, 5])

In [ ]:
np.setdiff1d(n,m)

array([6, 7])

In [ ]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [ ]:
m[np.in1d(m,1)]

array([1])

### np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [ ]:
# code
a

array([110, 530,  28,  50,  38,  37,  94,  92,   5,  30,  68,   9,  78,
         2,  21])

In [ ]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 28, 50, 38, 37, 75, 75, 25, 30, 68, 25, 75, 25, 25])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals